#!/bin/sh

[ -n "$DEVICE" ] || exit 0

[ "$ACTION" = ifup ] && /etc/init.d/nftables enabled && {
	/etc/init.d/nftables restart
	logger -t nftables "Restarting nftables due to $ACTION of $INTERFACE ($DEVICE)"
}

